/* Copyright © 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */package cn.zhuatech.airedteam.controller;import cn.zhuatech.airedteam.common.ApiResponse;import cn.zhuatech.airedteam.model.CampaignAudit;import cn.zhuatech.airedteam.service.RedTeamService;import jakarta.validation.Valid;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.security.core.Authentication;import org.springframework.web.bind.annotation.*;import java.util.*;/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           */
@RestController@RequestMapping("/api/ai-redteam")public class RedTeamController{private final RedTeamService service;/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                */
public RedTeamController(RedTeamService s){service=s;}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */
@PostMapping("/campaigns/run")@PreAuthorize("hasAnyRole('ADMIN','REDTEAM')")public ApiResponse<RedTeamService.CampaignResult>run(@Valid@RequestBody RedTeamService.CampaignRequest r,Authentication a){return ApiResponse.ok("红队活动运行完成",service.run(r,a.getName()));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           */
@GetMapping("/audits")@PreAuthorize("hasAnyRole('ADMIN','AUDITOR')")public ApiResponse<List<CampaignAudit>>audits(){return ApiResponse.ok("审计查询成功",service.audits());}}
