/* Copyright © 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */package cn.zhuatech.airedteam.repository;import cn.zhuatech.airedteam.model.CampaignAudit;import org.springframework.data.jpa.repository.JpaRepository;import java.util.*;/**
                                                                                                                                                                                                                                           * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                           */
public interface CampaignAuditRepository extends JpaRepository<CampaignAudit,Long>{/**
                                                                                                                                                                                                                                                                                                                              * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                              */
Optional<CampaignAudit>findByRequestId(String id);/**
                                                                                                                                                                                                                                                                                                                                                                                * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                */
List<CampaignAudit>findTop100ByOrderByCreatedAtDesc();}
